rollbar_flutter/README.md
Without this it fails to compile with:
Error: Method not found: 'ConfigBuilder'.
Documentation change to include a missing import. Note that this import is present in the `rollbar_flutter` example:
https://github.com/rollbar/rollbar-flutter/blob/33f18af7e4e799dacbbcf199c2ee1671c6df74cc/rollbar_flutter/example/lib/main.dart#L6
N/A
=> docs: Add missing import to example code

rollbar_flutter/ios/rollbar_flutter.podspec
This one-word change allows builds targeting the iOS Simulator on computers running the Apple M1 chipset.
None.
=> exclude arm64 slice for the iOS simulator

rollbar_flutter/example/pubspec.yaml
Fixes issue when resolving dependency for the Flutter example project reported in: https://github.com/rollbar/rollbar-flutter/issues/21.
`flutter pub get` should work fine now.
- [ x ] Bug fix (non-breaking change that fixes an issue)
- [ x ] Maintenance
- Fix https://github.com/rollbar/rollbar-flutter/issues/21
- [ x ] Lint rules pass locally
- [ x ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ x ] "Ready for review" label attached to the PR and reviewers assigned
- [ x ] Issue from task tracker has a link to this pull request
=> Fixes dependency issue #21

rollbar_flutter/example/android/app/src/main/AndroidManifest.xml
Another small build change that fixes https://github.com/rollbar/rollbar-flutter/issues/27 according to https://flutter.dev/go/android-project-migration.
The project already had Android embedding v2, but was seeing this specific line as reason enough to consider the project not Android embedding v2 compliant.
- [ x ] Bug fix (non-breaking change that fixes an issue)
- [ x ] Maintenance
- Fix https://github.com/rollbar/rollbar-flutter/issues/27
- [ x ] Lint rules pass locally
- [ x ] All tests related to the changed code pass in development
- [ x ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ x ] "Ready for review" label attached to the PR and …
=> Fixes build error related to Android embedding v2

rollbar_flutter/lib/src/rollbar.dart
I'm regularly encountering exceptions on the `!` cast for `details.stack`. This most often occurs on UI exceptions. 
- Fix [SC-]
- Fix #1
=> avoid null cast exceptions on FlutterError stack traces

rollbar_dart/pubspec.yaml, rollbar_flutter/pubspec.yaml
We re-add the `dependency_overrides` we use in development.
New versions of Dart have fixed this, but we're still supporting an older one.
A `0.3.0-beta` has been added @ https://github.com/rollbar/rollbar-flutter/releases/tag/0.3.0-beta.
=> Re-added development dependency_overrides

rollbar_dart/lib/src/sender/http_sender.dart
We were doing this through the `ConnectivityManager`, which was removed yesterday.
This adds the suspension back with the main goal of keeping this behavior for the next release.
A proper solution will come when https://github.com/rollbar/rollbar-flutter/issues/70 is addressed.
A proper solution will see the payload flow abstracted frp-style into a stream of payloads over time and just model the flow of time declaratively and without managing state instead of this horribleness.
- Related to https://github.com/rollbar/rollbar-flutter/pull/69
- Related to https://github.com/rollbar/rollbar-flutter/issues/70
=> Suspend http transactions for 30 seconds in case of failure

.github/workflows/ci.yml, rollbar_common/CHANGELOG.md, rollbar_common/pubspec.yaml, rollbar_dart/CHANGELOG.md, rollbar_dart/example/pubspec.yaml, rollbar_dart/lib/src/notifier/notifier.dart, rollbar_dart/pubspec.yaml, rollbar_flutter/CHANGELOG.md, rollbar_flutter/example/lib/main.dart, rollbar_flutter/example/pubspec.yaml, rollbar_flutter/pubspec.yaml
`0.4.0-beta` changes for publishing.
- New generic, functional `TableSet` collection that abstracts SQL declarations by allowing the management of sqlite3 tables as standard Dart `Set` collections over `Serializable` sealed immutable classes.
- Generic `zip` function for collections that allow to iterate two collections side by side.
- New functional language extensions on various Dart types and collections:
- `Iterable`, `Map`, `DateTime`, `Mirror`, `Random`, `String`, `Object`, and more.
- The `ConnectivityMonitor` has been removed.
- New feature: Telemetry.
- See all the breadcrumbs leading up to an error on Rollbar.
- Gather extra data silently by "dropping breadcrumbs" with information about UI navigation, app events, connectivity events, and more.
- Telemetry is only sent to Rollbar …
=> #72 Publish 0.4.0-beta

rollbar_dart/pubspec.yaml, rollbar_flutter/pubspec.yaml
Bring back the dev overrides we removed for publishing in order to let `pana` pass all checks in the CI.
=> Bring back dev overrides.

rollbar_common/lib/src/data/breadcrumb_record.dart, rollbar_common/lib/src/data/payload_record.dart, rollbar_common/lib/src/persistable.dart
Fixed an obscure compilation issue that arose while working on the current features. The error thrown by the analyzer/compiler is neither correct nor particularly precise, but it led to an improvement in how we express persistable records, which fixed the complain.
- Fix https://github.com/rollbar/rollbar-flutter/issues/76.
=> Fixed Dart compilation issue.

rollbar_flutter/android/build.gradle, rollbar_flutter/android/src/test/java/com/rollbar/flutter/RollbarMethodChannelTest.java, rollbar_flutter/example/lib/main.dart
An Android unit test started to fail with Flutter SDK 3.7.
The function `encodeErrorEnvelopeWithStacktrace` on our mocked `MethodCodec` is being called without a stack trace, this call comes from the Flutter system. I've tracked this down to:
- https://api.flutter.dev/javadoc/io/flutter/plugin/common/MethodCodec.html#encodeErrorEnvelopeWithStacktrace(java.lang.String,java.lang.String,java.lang.Object,java.lang.String)
Where "errorStacktrace - Platform stacktrace for the error. possibly null."
So it seems it is correct that this may be null. I've added a check.
The library and example works fine regardless of the Flutter SDK version.
- This issue isn't being tracked.
=> Fixes an Android native unit test and Android example issue

.github/workflows/ci.yml
This is a CI maintenance PR that bumps the Flutter version used to build to 3.10.2 and fixed the `runs-on` value that was specifying the ubuntu version instead of just using latest.
- Not tracked
=> Updated Flutter versions for the CI and fixed incorrect ubuntu version

rollbar_flutter/example/ios/Runner.xcodeproj/project.pbxproj, rollbar_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, rollbar_flutter/example/pubspec.yaml, rollbar_flutter/ios/Classes/RollbarFlutterPlugin.m, rollbar_flutter/ios/rollbar_flutter.podspec, rollbar_flutter/pubspec.yaml
This updates the SDK to use the latest Rollbar Apple SDK 3.x which is used for native-level crash collection and some advanced features.
For a full list of improvements included in the new Rollbar Apple SDK, refer to: https://github.com/rollbar/rollbar-apple/releases/tag/3.0.0.
This update also fixes the excessive logging associated with the previous version of the Apple SDK. It also allows us to use the latest platform-specific sqlite3 libraries available to Flutter.
The iOS example project has been updated accordingly to make use of the Rollbar Apple SDK 3.x.
This PR also bumps the SDK version to 1.4.0.
- Fix [SC-122326](https://app.shortcut.com/rollbar/story/122326/excessive-logging-of-processing-saved-items)
- Fixes https://github.com/rollbar/rollbar-flutter/issues/89
=> Use Rollbar Apple SDK 3 for native crash collection

rollbar_flutter/CHANGELOG.md, rollbar_flutter/example/pubspec.yaml, rollbar_flutter/ios/rollbar_flutter.podspec, rollbar_flutter/lib/src/rollbar.dart, rollbar_flutter/pubspec.yaml
This PR fixes a serious bug where the SDK wasn't properly hooking its `onError` callback to the Flutter framework which would prevent exceptions originating/or being caught by the Flutter Frameworks from being reported to Rollbar.
This PR also bumps the version to `1.4.1` as this is intended as a hot-fix to be published immediately upon merge.
=> Fixed onError callback not being set on the Flutter framework

rollbar_flutter/example/lib/main.dart, rollbar_flutter/lib/src/hooks/flutter_hook.dart, rollbar_flutter/lib/src/hooks/hook.dart, rollbar_flutter/lib/src/hooks/platform_hook.dart, rollbar_flutter/lib/src/rollbar.dart
This PR implements the new recommended method to catch exceptions that don't occur within Flutter's callbacks according to https://docs.flutter.dev/testing/errors.
This swizzles the `PlatformDispatcher.onError` callback with our own callback which also calls the original one.
Previously, we were using a custom `Zone` to catch this class of exceptions but it was [deprecated in Flutter 3.3](https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff#:~:text=In%20this%20release%2C%20instead%20of%20using%20a%20custom%20Zone%2C%20you%20should%20catch%20all%20errors%20and%20exceptions%20by%20setting%20the%20PlatformDispatcher.onError%20callback).
We aim to preserve compatibility with Flutter < 3.3.
- Resolves [SC-129017](https://app.shortcut.com/rollbar/story/129017/flutter-sdk-isn-t-catchi …
=> Use new PlatformDispatcher onError method if available

rollbar_flutter/lib/src/hooks/native_hook.dart, rollbar_flutter/lib/src/hooks/platform_hook.dart, rollbar_flutter/lib/src/method_channel.dart, rollbar_flutter/lib/src/rollbar.dart
This PR encapsulates the initialization of the Rollbar/Android (native) SDK as another `Hook`, called the `NativeHook`.
This PR also encapsulate inside the `PlatformHook` the `as dynamic` hack we use to check whether the `PlatformDispatcher.onError` closure exists.
- Related to [SC-129017](https://app.shortcut.com/rollbar/story/129017/flutter-sdk-isn-t-catching-async-errors)
=> Initialize the native Rollbar/Android SDK as a hook instead of explicitly

rollbar_flutter/CHANGELOG.md, rollbar_flutter/example/pubspec.yaml, rollbar_flutter/ios/rollbar_flutter.podspec, rollbar_flutter/pubspec.yaml
This PR updates the changelog and version to 1.4.2.
=> Release 1.4.2

rollbar_common/pubspec.yaml, rollbar_dart/pubspec.yaml
> Please include a summary of the change and which issues are fixed.
closes:  #115
`rollbar-flutter` cant really be used in newer flutter apps as the version of `http` and `uuid` are out of date. This simply bumps those packages. 
> Please also include relevant motivation and context.
- Fix #115
=> chore: Bumping http & uuid versions

rollbar_flutter/android/build.gradle
Gradle 8 no longer allows the `xml.enbled true` method call and now uses the `xml.required= true` property.
https://github.com/rollbar/rollbar-flutter/issues/119
- [N/A] The code changed/added as part of this pull request has been covered with tests
- [N/A] All tests related to the changed code pass in development
=> Replace removed `enabled` Gradle method calls with `required` properties

rollbar_flutter/ios/rollbar_flutter.podspec
This PR addresses [issue #136](https://github.com/rollbar/rollbar-flutter/issues/136), which reports build failures on iOS when using Xcode 18. To resolve this, the internal dependency RollbarNotifier has been updated to version 3.3.3. This update ensures compatibility with Xcode 18 and resolves the iOS build 
- Fix [#136](https://github.com/rollbar/rollbar-flutter/issues/136)
=> Update RollbarNotifier dependency to 3.3.3
